version: '3'
services:
  web:
    image: nginx
    ports:
      - 8443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert.key:/etc/nginx/cert.key:ro
      - ./cert.pem:/etc/nginx/cert.pem:ro
